#!/bin/bash

#controllo quale sia il mio environment (Linux, Mac) perché cambia il base path dove è installato DRC
case "$(uname -s)" in

   Darwin)
     CONFIG_DIR="/usr/local/share/drc/config/44.1 kHz"
     ;;

   Linux)
     CONFIG_DIR=/usr/share/drc/config
     ;;

   *)
     exit 1
     ;;
esac

RAW_EXT=pcm
DRC_EXT=drc
DEFAULT_NAME_MIC_COMPENSATION_FILE=mic_compensation_file
DEFAULT_NAME_TARGET_CURVE_FILE=target_curve_file
DRC_CONFIGURATION_FILE_PREFIX=erb
DRC_CONFIGURATION_FILE_FREQUENCY=44.1
IMPULSE_RESPONSE_RAW_FILE_PREFIX=impulse_response_raw
MIC_COMPENSATED_IMPULSE_RESPONSE_PREFIX=mic_compensated_impulse_response
MINIMUM_PHASE_PREFIX=minimum_phase
TEST_CONVOLUTION_PREFIX=test_convolution
OUT_DIR=out

IMPULSE_RESPONSE_BIT_DEPTH=32
OPERATING_FREQUENCY=44100
A_FACTOR_EP_LOWER_WINDOW=24
START_FREQ=20
END_FREQ=20000
PEAK_LIMITING_MAX_GAIN=2

function print_help {
 echo >&2
 echo "drc is intended to be used with 441000 Hz files but other frequency configuration files are provided but they aren't tested" >&2
 echo >&2
 echo "when exporting impulse response please be sure it is a signed integer 32 bit wav" >&2
 echo >&2
 echo "USAGE drcwrapper -f [...] -c [...] -m [...] -t [...] -s [...] -e [...] -p [...] -l [...] -u [...] -g [...] IMPULSE" >&2
 echo >&2
 echo "-b 	impulse response bit depth. Default is 32" >&2
 echo "-f 	operating frequency. It can be 44100, 48000, 88200 or 96000. Default is 44100" >&2
 echo "-c 	DRC configuration preset (minimal, soft, normal, strong, extreme, insane, erb" >&2
 echo "-m 	mic compensation file" >&2
 echo "-t 	target curve" >&2
 echo "-s 	lower end frequency that your speaker can reproduce" >&2
 echo "-e 	higher end frequency that your speaker can reproduce" >&2
 echo "-p   window exponent. Increasing it gives higher correction in the midrange. Typical values are between 0.7 and 1.2" >&2
 echo "-l   lower correction window in milliseconds" >&2
 echo "-u   upper correction window in milliseconds" >&2
 echo "-g   Maximum gain allowed in the correction filter. Peaks in the correction filter amplitude response greater than this value will be compressed to PLMaxGain. Typical values are between 1.2 and 4. A typical value is 2.0, i.e. 6 dB." >&2
 echo >&2
}

function evaluate_help {
 if [ $1 = "-h" -o $1 = "--help" ]; then
  print_help;
  exit 1
 fi
}

#il primo parametro è il nome del file da creare
#il secondo è la frequenza di campionamento
#l'ultima riga del file deve essere la frequenza
#di campionamento fratto 2
function print_flat_file {
  touch $1
  echo -e "0 -30\n$(($2 / 2)) -30" >> $1
}


function set_operating_frequency {
  case $1 in
   "44100")
       DRC_CONFIGURATION_FILE_FREQUENCY=44.1
       OPERATING_FREQUENCY=44100
       ;;
   "48000")
       DRC_CONFIGURATION_FILE_FREQUENCY=48.0
       OPERATING_FREQUENCY=48000
       ;;
   "88200")
       DRC_CONFIGURATION_FILE_FREQUENCY=88.2
       OPERATING_FREQUENCY=88200
       ;;
   "96000")
       DRC_CONFIGURATION_FILE_FREQUENCY=96.0
       OPERATING_FREQUENCY=96000
       ;;
  esac
}


#calculate using bc
function calculate_bc {
  echo $(echo "$1" | bc)
}


function calculate_start_freq {
  echo $(calculate_bc "$1 * 2")
}


function calculate_end_freq {
  echo $(calculate_bc "$1 / 2")
}


#calculate window taps from milliseconds
function calculate_window_taps {
  echo $(calculate_bc "$1 * $OPERATING_FREQUENCY / 500")
}


function calculate_ep_lower_window_taps {
  echo $(calculate_bc "$1 / $A_FACTOR_EP_LOWER_WINDOW")
}


function calculate_is_pe_lower_window_taps {
  echo $(calculate_bc "$1 / 2")
}


function calculate_is_pe_upper_window_taps {
  echo $(calculate_bc "$1 * 75 / 100")
}


NUM_ARGS=$#

case $NUM_ARGS in
 "0")
     print_help;
     exit 1
     ;;
 "1")
     evaluate_help $1;
     ;;
esac


#ho messo alcuni parametri, posso creare la cartella di lavoro
mkdir $OUT_DIR


while getopts ":b:f:c:m:t:s:e:p:l:u:g:" OPTIONS; do
  case $OPTIONS in
    b)
      IMPULSE_RESPONSE_BIT_DEPTH=$OPTARG
      ;;
    f)
      set_operating_frequency $OPTARG
      ;;
    c)
      DRC_CONFIGURATION_FILE_PREFIX=$OPTARG
      ;;
    m)
      MIC_COMP_FILE=$OPTARG
      ;;
    t)
      TARGET_CURVE=$OPTARG
      ;;
    s)
	  # Start frequency where the reference RMS level used for peak limiting is computed. Default value set to 100 Hz.
	  # This value should be set typically to something like an octave above the minimum reproducible frequency of your speakers.
      START_FREQ=$(calculate_start_freq $OPTARG)
      ;;
    e)
	  # End frequency where the reference RMS level used for peak limiting is computed. Default value set to 10000 Hz.
	  # This value should be set typically to something like an octave below the maximum reproducible frequency of your speakers.
      END_FREQ=$(calculate_end_freq $OPTARG)
      ;;
    p)
      WINDOW_EXPONENT=$OPTARG
      ;;
    l)
      LOWER_WINDOW_TAPS=$(calculate_window_taps $OPTARG)
      EP_LOWER_WINDOW_TAPS=$(calculate_ep_lower_window_taps $LOWER_WINDOW_TAPS)
      IS_PE_LOWER_WINDOW_TAPS=$(calculate_is_pe_lower_window_taps $EP_LOWER_WINDOW_TAPS)
      IS_PE_UPPER_WINDOW_TAPS=$(calculate_is_pe_upper_window_taps $IS_PE_LOWER_WINDOW_TAPS)
      ;;
    u)
      UPPER_WINDOW_TAPS=$(calculate_window_taps $OPTARG)
      ;;
    g)
      PEAK_LIMITING_MAX_GAIN=$OPTARG
      ;;
    :)
      echo "Error: option ${OPTARG} requires an argument"
      echo
      print_help;
      exit 1
      ;;
    ?)
      echo "Invalid option: ${OPTARG}"
      echo
      print_help;
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))


#gestisco il caso che non abbia una correzione per il microfono oppure non abbia impostato una curva target
if [ -z "$MIC_COMP_FILE" ]; then
  print_flat_file $DEFAULT_NAME_MIC_COMPENSATION_FILE $OPERATING_FREQUENCY
  MIC_COMP_FILE=$DEFAULT_NAME_MIC_COMPENSATION_FILE
fi

if [ -z "$TARGET_CURVE" ]; then
  print_flat_file $DEFAULT_NAME_TARGET_CURVE_FILE $OPERATING_FREQUENCY
  TARGET_CURVE=$DEFAULT_NAME_TARGET_CURVE_FILE
fi


INPUT_FILE=$1
FILENAME=$(basename $INPUT_FILE | sed 's/\.[^.]*$//')
OUTPUT_FILE="${FILENAME}.${RAW_EXT}"

IMPULSE_RESPONSE_RAW_FILE="${IMPULSE_RESPONSE_RAW_FILE_PREFIX}_${OUTPUT_FILE}"
MIC_COMPENSATED_IMPULSE_RESPONSE_FILE="${MIC_COMPENSATED_IMPULSE_RESPONSE_PREFIX}_${OUTPUT_FILE}"
DRC_OUTPUT_FILE=$OUTPUT_FILE
DRC_OUTPUT_MINIMUM_PHASE_FILE="${MINIMUM_PHASE_PREFIX}_${OUTPUT_FILE}"
DRC_OUTPUT_TEST_CONVOLUTION_FILE="${TEST_CONVOLUTION_PREFIX}_${OUTPUT_FILE}"
DRC_CONFIGURATION_FILE="${CONFIG_DIR}/${DRC_CONFIGURATION_FILE_PREFIX}-${DRC_CONFIGURATION_FILE_FREQUENCY}.${DRC_EXT}"


# converto i file dal formato di uscita di REW (signed integer) ad un formato comprensibile per DRC (floating point 32 bit)
sox -t wav -e signed-integer -b $IMPULSE_RESPONSE_BIT_DEPTH -r $OPERATING_FREQUENCY -c 1 $INPUT_FILE -t raw -e floating-point -b 32 -r $OPERATING_FREQUENCY -c 1 $OUT_DIR/$IMPULSE_RESPONSE_RAW_FILE

DRC="drc --BCInFile=$OUT_DIR/$IMPULSE_RESPONSE_RAW_FILE --MCFilterType=M --MCPointsFile=$MIC_COMP_FILE --MCOutFile=$OUT_DIR/$MIC_COMPENSATED_IMPULSE_RESPONSE_FILE --MPWindowExponent=$WINDOW_EXPONENT --EPWindowExponent=$WINDOW_EXPONENT --RTWindowExponent=$WINDOW_EXPONENT --MPLowerWindow=$LOWER_WINDOW_TAPS --MPUpperWindow=$UPPER_WINDOW_TAPS --EPLowerWindow=$EP_LOWER_WINDOW_TAPS --EPUpperWindow=$UPPER_WINDOW_TAPS --RTLowerWindow=$LOWER_WINDOW_TAPS --RTUpperWindow=$UPPER_WINDOW_TAPS --ISPETType=f --ISPELowerWindow=$IS_PE_LOWER_WINDOW_TAPS --ISPEUpperWindow=$IS_PE_UPPER_WINDOW_TAPS --PLStartFreq=$START_FREQ --PLEndFreq=$END_FREQ --PSPointsFile=$TARGET_CURVE --PLMaxGain=$PEAK_LIMITING_MAX_GAIN --PSOutFile=$OUT_DIR/$DRC_OUTPUT_FILE --MSOutFile=$OUT_DIR/$DRC_OUTPUT_MINIMUM_PHASE_FILE --TCOutFile=$OUT_DIR/$DRC_OUTPUT_TEST_CONVOLUTION_FILE $DRC_CONFIGURATION_FILE"

echo "executing drc..."
echo
echo $DRC
echo
eval $DRC

echo
echo "cleaning..."
rm $OUT_DIR/$IMPULSE_RESPONSE_RAW_FILE